Lab03_DuongQuocAn/Controllers/RubikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab03_DuongQuocAn.Models;
using PagedList;

namespace Lab03_DuongQuocAn.Controllers
{
    public class RubikController : Controller
    {
        // GET: Rubik
        public ActionResult Index(int? page, string searchString)
        {
            ViewBag.Keyword = searchString;
            if (page == null)
                page = 1;
            int pageSize = 3;
            return View(Rubik.getAll(searchString).ToPagedList(page.Value, pageSize));
        }

        // GET: Rubik/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpNotFound();
            Rubik find = Rubik.FindRubikByID(id.Value);
            if (find == null)
                return HttpNotFound();
            return View(find);
        }

        // GET: Rubik/Create
        public ActionResult Create()
        {
            List<Loai> maloai = Loai.getAll();
            List<SelectListItem> item = new List<SelectListItem>();
            foreach (var i in maloai)
            {
                item.Add(new SelectListItem
                {
                    Text = i.tenloai,
                    Value = i.maloai.ToString()
                });

            }
            ViewBag.maloai = item;
            return View(new Rubik());
        }

        // POST: Rubik/Create
        [HttpPost]
        public ActionResult Create(Rubik newrubik)
        {
            if (ModelState.IsValid)
            {
                newrubik.insert();
                return RedirectToAction("Index");
            }
            else
                return View("Create", newrubik);
        }

        // GET: Rubik/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpNotFound();
            Rubik find = Rubik.FindRubikByID(id.Value);
            if (find == null)
                return HttpNotFound();
            List<Loai> maloai = Loai.getAll();
            List<SelectListItem> item = new List<SelectListItem>();
            foreach (var i in maloai)
            {
                item.Add(new SelectListItem
                {
                    Text = i.tenloai,
                    Value = i.maloai.ToString()
                });

            }
            ViewBag.maloai = item;
            return View(find);
        }

        // POST: Rubik/Edit/5
        [HttpPost]
        public ActionResult Edit(Rubik rubikEdit)
        {
            if (ModelState.IsValid)
            {
                rubikEdit.Update();
                return RedirectToAction("Index");
            }
            else
                return View("Index", rubikEdit);
        }

        // GET: Rubik/Delete/5
        public ActionResult Delete(int? id)
        {
            RubikModel context = new RubikModel();
            var delete = context.Rubik.FirstOrDefault(p => p.id == id);
            return View(delete);
        }

        // POST: Rubik/Delete/5
        [HttpPost]
        public ActionResult Delete(Rubik rubikDel)
        {
            try
            {
                RubikModel context = new RubikModel();
                var delete = context.Rubik.FirstOrDefault(p => p.id == rubikDel.id);
                context.Rubik.Remove(delete);
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("Index");
        }



        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "/Content/images/" + file.FileName;
        }
    }
}

Lab03_DuongQuocAn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DƯƠNG QUỐC AN", "Index", "Rubik", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="font-size: 22px">
                    <li>@Html.ActionLink("RUBIK", "Index", "Rubik")</li>
                    <li>@Html.ActionLink("About", "Index", "Rubik")</li>
                    <li>@Html.ActionLink("Contact", "Index", "Rubik")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dương Quốc An</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("upload", required: false)
    @RenderSection("scripts", required: false)
</body>
</html>